#!/bin/bash

folder_name="/app/ysztest/data/"
filesCount=0
linesCount=0
echo "$folder_name"
function funCount()
{
	for file in `ls $folder_name`
	do
		declare -i fileLines
		fileLines=`sed -n '$=' $folder_name"/"$file`	
		let linesCount=$linesCount+$fileLines
		let filesCount=$filesCount+1
	done	

}


funCount
echo "file number is $filesCount"
echo "$linesCount"
